

services:
  wifi-login:
    build:
      context: ./Wifi_AutoLogin
    container_name: wifi-auto-login
    restart: always
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://www.google.com"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  portainer_data: