

services:
  wifi-login:
    build:
      context: ./Wifi_AutoLogin
    container_name: wifi-auto-login
    restart: always
    environment:
      - PYTHONUNBUFFERED=1

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: